name = "Quarantine Pack"
author = "Tom_The_Geek"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b3e2c69f34fd948ac71bed8bf69b22bda3278796e8db768b3cff62d713c0405"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
