name = "Quarantine Pack"
author = "Tom_The_Geek"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c14961dd90152c151dd96452ec1e2702f019770243b1c5384b92cddada147224"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
