name = "Quarantine Pack"
author = "Tom_The_Geek"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68364e694e031fb14476f23a66353738e4b93a5725ab08ceda013e17ea4edcd0"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
